title: FastAPI
description: [A short description of your site's purpose]
author: Jakie Chan
theme: jekyll-theme-Minima

# jekyll-theme-Dinky
# ###################
# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Merlot
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine
