title: [The title of your site]
description: [A short description of your site's purpose]
theme: jekyll-theme-Cayman

# Architect
# Cayman
# Dinky
# Hacker
# Leap day
# Merlot
# Midnight
# Minima
# Minimal
# Modernist
# Slate
# Tactile
# Time machine
